---
name: ""
surname: "Robert Cline"
position: "Land Manager"
address: "Sidney, Nebraska"
profilepic: "./img/me.jpg"
www: "robertcclinesr.com"
email: "rccline@fastmail.fm"
github: rccline
linkedin: robertccline
orcid:  0000-0003-4758-3111
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: "AAPL Certified Professional Landman, with a work history managing land activities for leasehold, fee, contractual interests, title curative, drafting and negotiating agreements. History of supervisory work managing teams, negotiators, performing due diligence, A&D, employing technological skills to automate workflow for title analysis, reporting and GIS mapping. I have coding and analytical skills which are directly transferable to other industries."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

### MIKTEX Updates https://miktex.org/howto/update-miktex 
### remotes::install_github('yihui/tinytex')  FAILS
require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Employment

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )

```

\pagebreak

# Skills

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```

# Honors

```{r HONORS}

honors %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

# Projects

```{r PROJECTS}

projects %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

# Works

```{r WORKS}

works %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

\pagebreak

# Certifications

```{r CERTIFICATIONS}

certifications %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```
